version: "3"

volumes:
  web:

services:
  first:
    build:
      main/
    restart: always
    ports: 
      - 8080:8080
    environment:
      - TZ=Europe/Moscow
    
  second:
    build:
      proj2/
    